const today = new Date();
const fiveYearsAgo = new Date();
fiveYearsAgo.setFullYear(today.getFullYear() - 5);

// Format as 'YYYY/MM/DD'
const formatDate = date =>
  `${date.getFullYear()}/${String(date.getMonth() + 1).padStart(
    2,
    '0',
  )}/${String(date.getDate()).padStart(2, '0')}`;

const startDate = formatDate(fiveYearsAgo);
const endDate = formatDate(today);

const SearchParams = {
  AllSearch: {
    BusinessType: 'A',
    PremiumsPending: false,
    ClaimPending: false,
    Flagged: false,
    BadClaims: false,
    DebitOutstanding: false,
    PolicyNumber: '',
    VehicleNumber: '',
    StartFromDt: startDate,
    StartToDt: endDate,
    TodayReminders: false,
    MobileNumber: '',
    AgentCode: 905717,
    NicNumber: '',
    BusiRegNo: '',
  },
  MotorSearch: {
    BusinessType: 'M',
    PremiumsPending: false,
    ClaimPending: false,
    Flagged: false,
    BadClaims: false,
    DebitOutstanding: false,
    PolicyNumber: '',
    VehicleNumber: '',
    StartFromDt: startDate,
    StartToDt: endDate,
    TodayReminders: false,
    MobileNumber: '',
    AgentCode: 905717,
    NicNumber: '',
    BusiRegNo: '',
  },

  NonMotorSearch: {
    BusinessType: 'G',
    PremiumsPending: false,
    ClaimPending: false,
    Flagged: false,
    BadClaims: false,
    DebitOutstanding: false,
    PolicyNumber: '',
    VehicleNumber: '',
    StartFromDt: startDate,
    StartToDt: endDate,
    TodayReminders: false,
    MobileNumber: '',
    AgentCode: 905717,
    NicNumber: '',
    BusiRegNo: '',
  },
  premiumPending: {
    BusinessType: 'A',
    PremiumsPending: true,
    ClaimPending: false,
    Flagged: false,
    BadClaims: false,
    DebitOutstanding: false,
    PolicyNumber: '',
    VehicleNumber: '',
    StartFromDt: startDate,
    StartToDt: endDate,
    TodayReminders: false,
    MobileNumber: '',
    AgentCode: 905717,
    NicNumber: '',
    BusiRegNo: '',
  },
  debitOutstanding: {
    BusinessType: 'A',
    PremiumsPending: false,
    ClaimPending: false,
    Flagged: false,
    BadClaims: false,
    DebitOutstanding: true,
    PolicyNumber: '',
    VehicleNumber: '',
    StartFromDt: startDate,
    StartToDt: endDate,
    TodayReminders: false,
    MobileNumber: '',
    AgentCode: 905717,
    NicNumber: '',
    BusiRegNo: '',
  },
  claimPending: {
    BusinessType: 'A',
    PremiumsPending: false,
    ClaimPending: true,
    Flagged: false,
    BadClaims: false,
    DebitOutstanding: false,
    PolicyNumber: '',
    VehicleNumber: '',
    StartFromDt: startDate,
    StartToDt: endDate,
    TodayReminders: false,
    MobileNumber: '',
    AgentCode: 905717,
    NicNumber: '',
    BusiRegNo: '',
  },
  remindersSet: {
    BusinessType: 'A',
    PremiumsPending: false,
    ClaimPending: false,
    Flagged: false,
    BadClaims: false,
    DebitOutstanding: false,
    PolicyNumber: '',
    VehicleNumber: '',
    StartFromDt: startDate,
    StartToDt: endDate,
    TodayReminders: true,
    MobileNumber: '',
    AgentCode: 905717,
    NicNumber: '',
    BusiRegNo: '',
  },
};

export default SearchParams;
